// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	compute "github.com/alukart32/go-fast-key/internal/database/compute"

	mock "github.com/stretchr/testify/mock"
)

// RequestParser is an autogenerated mock type for the RequestParser type
type RequestParser struct {
	mock.Mock
}

// Parse provides a mock function with given fields: req
func (_m *RequestParser) Parse(req string) (compute.Query, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 compute.Query
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (compute.Query, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(string) compute.Query); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(compute.Query)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRequestParser creates a new instance of RequestParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRequestParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *RequestParser {
	mock := &RequestParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
