engine:
  type: "in_memory"
  partitions_number: 8
network:
  address: "127.0.0.1:8080"
  max_connections: 100
  max_message_size: "4KB"
  idle_timeout: 5m
logging:
  level: "debug"
  output: "./fastkey.log"